### ISSUE TITLE
Code 4 feedback

### ISSUE THREAD

**Issue by bigfatnoob** [fairanswers/fss16joe#1]
Your code might need improvement. Ideally after 1000 gens, your solution should be close to x=1. Your best solution is at x=-3741. Run it multiple times and see if it ends up close to this or check if there is a bug in your code. If you have trouble understanding SA, come talk to me.

**Comment by fairanswers** [comment]
George,

You were right.  Thanks for the heads up.  After looking at it for ENTIRELY
too long, I realized I never updated the best energy when I found the best
solution.  Instead of getting better, it jumped around randomly and just
reported the first solution as 'best'.

Let me know if this looks better.

http://tiny.cc/ase16joefCodeHw4

Thanks,
Joe

**Comment by bigfatnoob** [comment]
Looks better.
